import { lazy, Suspense, useMemo, useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { DecisionEvidence } from "./components/DecisionEvidence";
import { DeploymentTimeline } from "./components/DeploymentTimeline";
import { Header } from "./components/Header";
import { MetricsStrip } from "./components/MetricsStrip";
import { ScenarioControls } from "./components/ScenarioControls";
import { StoryPanel } from "./components/StoryPanel";
import { generatedPlans, scenarios } from "./data/caseStudy";
import { runScenarioPlan } from "./model/planner";
import type { ScenarioId } from "./types";
import "./styles.css";

const NetworkMap = lazy(() =>
  import("./components/NetworkMap").then((module) => ({
    default: module.NetworkMap,
  })),
);

const TradeoffChart = lazy(() =>
  import("./components/TradeoffChart").then((module) => ({
    default: module.TradeoffChart,
  })),
);

export default function V1Planner() {
  const [selectedScenario, setSelectedScenario] =
    useState<ScenarioId>("baseline");
  const [annualCapital, setAnnualCapital] = useState(120);
  const [maxDistance, setMaxDistance] = useState(20);
  const [appliedCapital, setAppliedCapital] = useState(120);
  const [appliedDistance, setAppliedDistance] = useState(20);
  const [isRunning, setIsRunning] = useState(false);
  const [showConfirmation, setShowConfirmation] = useState(false);

  const scenario =
    scenarios.find((item) => item.id === selectedScenario) ?? scenarios[0];

  const result = useMemo(
    () => runScenarioPlan(scenario, appliedCapital, appliedDistance),
    [scenario, appliedCapital, appliedDistance],
  );

  const runScenario = () => {
    setIsRunning(true);
    setShowConfirmation(false);
    window.setTimeout(() => {
      setAppliedCapital(annualCapital);
      setAppliedDistance(maxDistance);
      setIsRunning(false);
      setShowConfirmation(true);
    }, 550);
  };

  const reset = () => {
    setSelectedScenario("baseline");
    setAnnualCapital(120);
    setMaxDistance(20);
    setAppliedCapital(120);
    setAppliedDistance(20);
    setShowConfirmation(false);
  };

  return (
    <>
      <Header />
      <main id="overview">
        <div className="primary-layout">
          <StoryPanel
            scenarios={scenarios}
            selectedScenario={selectedScenario}
            onScenarioChange={setSelectedScenario}
            onRun={runScenario}
          />
          <Suspense fallback={<div className="map-panel loading-panel">Loading map…</div>}>
            <NetworkMap sites={result.activeSites} />
          </Suspense>
          <ScenarioControls
            scenarios={scenarios}
            selectedScenario={selectedScenario}
            annualCapital={annualCapital}
            maxDistance={maxDistance}
            isRunning={isRunning}
            onScenarioChange={setSelectedScenario}
            onCapitalChange={setAnnualCapital}
            onDistanceChange={setMaxDistance}
            onRun={runScenario}
            onReset={reset}
          />
        </div>

        <MetricsStrip result={result} />

        <div className="analysis-layout">
          <DecisionEvidence />
          <Suspense
            fallback={
              <section className="tradeoff-panel loading-panel">
                Loading scenario comparison…
              </section>
            }
          >
            <TradeoffChart
              scenarios={scenarios}
              selectedScenario={selectedScenario}
            />
          </Suspense>
          <DeploymentTimeline phases={generatedPlans[selectedScenario].phasePlan} />
        </div>

        <section className="method-section" id="method">
          <div>
            <h2>From classroom model to decision product</h2>
            <p>
              The rebuild separates source data, scenario assumptions, model
              logic, and presentation. Scenario baselines are generated by the
              v1 mixed-integer optimization model; live slider changes provide
              a fast sensitivity estimate around each solved plan.
            </p>
          </div>
          <ol>
            <li>
              <strong>Locate</strong>
              Candidate sites and demand zones
            </li>
            <li>
              <strong>Optimize</strong>
              Capital, capacity, coverage, and grid timing
            </li>
            <li>
              <strong>Explain</strong>
              Trade-offs, phases, and managerial implications
            </li>
          </ol>
        </section>
      </main>

      {showConfirmation && (
        <div className="confirmation" role="status">
          <CheckCircle2 size={18} />
          Scenario updated
        </div>
      )}
    </>
  );
}
